version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: leonefesch/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static
      - media:/app/media
  frontend:
    env_file: .env
    image: leonefesch/kittygram_frontend
    command: cp -r /app/build/. /static/
    restart: no
    volumes:
      - static:/static
  gateway:
    image: leonefesch/kittygram_gateway
    env_file: .env
    restart: on-failure
    ports:
      - $PORT_NGINX:80
    volumes:
      - static:/static
      - media:/app/media
